values = 0

#run, runner and set are loop counters. I have added separate counters for each game 
# as well as the total number of games played so that I can change the run number of
#games while not affecting the number of coin toss
run = 1:100
runner = 1:3
set = 1:5

#This loop will run each set of games. For example, if suppose we want to play 10
#games for 1 pound each, we use this loop to run each of those 10 games as 
#many times as we want to calculate an average of all those games.
for(k in set){
  
  print(paste("Set ", k))
  cat("===============================================================\n")
  
  #After each set finishes, these values are reset so that it records the correct
  #value and does not overlap on the previous ones.
  winnings = 0
  temp = 0
  
  #This loop is for the number of games to be played. To explain briefly, this is 
  #like playing the game from the beginning. It will set the amount to whatever was
  #payed in the beginning. 
  for(j in runner) {
    
    #Set the amount here for each time we play
    amount = 2
    
    print(paste("Game Number: ", j ))
    print("===================================")
    
    #This loop is for each game. This will run for each time
    #you payed to play. The number of time you need to play this game can be set in
    #the previous loop.
    for(i in run){
      
      #Loop generating one value from the sample. It will also print what was 
      #generated by the sample.
      test = (sample(c("Heads","Tails"),1, replace = TRUE))
      print(test)
      
      #if the sample generates tails, it will double the amount here and will
      #continue the for loop
      if (test == "Tails") {
        
        amount <- amount * 2
      } 
      
      #if sample generates heads, it will print the amount you have won, it it 
      #didn't generate heads, and then with the break command it will exit the 
      #loop, meaning the game is over
      else {
        
        print(paste("You have won ",amount ," Pounds in this game."))
        cat("\n")
        break
      }
    }
    
    #this will store the prize money from each game the player has won
    winnings <- winnings + amount
  }
  
  #This value will record all the winnings from each set of game.
  values[k] = winnings
  cat("\n")
  print(paste("Total winnings of that set: ", winnings))
  
  #The prize won in different game will be plotted and then saved to a csv file.  
  #plot(prize)
  #write.table(table(prize), sep = " ", quote = FALSE,  row.names = FALSE)
  #write.table(table(prize), file = "C:/Users/EDWIN/Data1.csv", sep = "," , quote = FALSE, row.names = FALSE)
  cat("\n")
}

#printing, plotting the winnings of each game. These values can be saved to 
# a CSV file as well
write.csv(values, file = "C:/Users/EDWIN/Data1.csv", quote = FALSE, row.names = TRUE)
print(values)
plot(values)

#To print the winnings of each game set-wise
#this can be used if there is a large set of data you are running in the code
for(l in set)
  print(paste("Amount won in SET ", l, " :", values[l]))
